name: Build and Deploy Soupault Site

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OPAMYES: "true"
      OPAMCONFIRMLEVEL: unsafe-yes
      OPAMNOAUTO: "1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.0

      - name: Initialize Opam and install Soupault
        run: |
          opam init --bare -a -y
          eval $(opam env)
          opam install -y soupault

      - name: Build site
        run: |
          eval $(opam env)
          soupault

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: main
          force_orphan: true
