name: Build and Deploy Site

on:
  push:
    branches: [main]  # Change to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install Lua
      run: |
        sudo apt update
        sudo apt install -y lua5.4

    - name: Install Soupault
      env:
        SOUPAULT_VERSION: 5.0.0
      run: |
        wget https://github.com/PataphysicalSociety/soupault/releases/download/${SOUPAULT_VERSION}/soupault-${SOUPAULT_VERSION}-linux-x86_64.tar.gz
        tar xvf soupault-${SOUPAULT_VERSION}-linux-x86_64.tar.gz
        sudo mv -v ./soupault-${SOUPAULT_VERSION}-linux-x86_64/soupault /usr/bin/

    - name: Run Lua preprocessing
      run: lua5.4 preprocess.lua

    - name: Build the site
      run: soupault

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Make sure this matches your Soupault output folder
