name: Build and Deploy Site

on:
  push:
    branches: [main]  # Change this to your default branch (like 'master' or 'main')

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install Soupault
      env:
        SOUPAULT_VERSION: 5.0.0
      run: |
        wget https://github.com/PataphysicalSociety/soupault/releases/download/${SOUPAULT_VERSION}/soupault-${SOUPAULT_VERSION}-linux-x86_64.tar.gz
        tar xvf soupault-${SOUPAULT_VERSION}-linux-x86_64.tar.gz
        sudo mv -v ./soupault-${SOUPAULT_VERSION}-linux-x86_64/soupault /usr/bin/

    - name: Run Lua/Python Preprocessing (optional)
      run: |
        lua preprocess.lua
        python preprocess.py

    - name: Build the site
      run: soupault

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Adjust if your output folder is different
