jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install Lua
      run: |
        sudo apt update
        sudo apt install -y lua5.4

    - name: Install Python dependencies (optional)
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt || true

    - name: Install Soupault
      env:
        SOUPAULT_VERSION: 5.0.0
      run: |
        wget https://github.com/PataphysicalSociety/soupault/releases/download/${SOUPAULT_VERSION}/soupault-${SOUPAULT_VERSION}-linux-x86_64.tar.gz
        tar xvf soupault-${SOUPAULT_VERSION}-linux-x86_64.tar.gz
        sudo mv -v ./soupault-${SOUPAULT_VERSION}-linux-x86_64/soupault /usr/bin/

    - name: Run Lua/Python preprocessing
      run: |
        lua5.4 preprocess.lua
        python3 preprocess.py

    - name: Build the site
      run: soupault

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build

