name: Build and Deploy Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Lua 5.4
      run: |
        sudo apt update
        sudo apt install -y lua5.4

    - name: Install Pandoc
      run: sudo apt install -y pandoc

    - name: Install Soupault
      env:
        SOUPAULT_VERSION: 5.0.0
      run: |
        wget https://github.com/PataphysicalSociety/soupault/releases/download/${SOUPAULT_VERSION}/soupault-${SOUPAULT_VERSION}-linux-x86_64.tar.gz
        tar xvf soupault-${SOUPAULT_VERSION}-linux-x86_64.tar.gz
        sudo mv -v ./soupault-${SOUPAULT_VERSION}-linux-x86_64/soupault /usr/bin/

    - name: Build the site with Soupault
      run: soupault

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
 


